// Generated by scripts/export_unity.py from range_10m.glb -- do not hand-edit; rebuild
// the hall and re-run the exporter instead, so Unity cannot drift from the model.
//
// Put this file anywhere under Assets/Editor/. Three menu items under Tools > Range:
//   Fix Materials (URP)   FBX carries a Phong approximation, so smoothness, metallic,
//                         emission and the two glass materials all arrive wrong. This
//                         restores them from the glTF values.
//   Build Ceiling Lights  FBX cannot carry usable lights; these are the model's own 35
//                         lamps, created as BAKED point lights.
//   Add Colliders         Mesh colliders on the surfaces you can walk into, nothing else.
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

public static class RangeSetup
{
    // Unity's point-light intensity is a unitless multiplier, not photometric candela.
    // This divisor converts; raise it if the bake comes out hot, lower it if flat.
    const float CandelaPerUnit = 1000f;

    struct Mat { public string name; public Color color; public float alpha, rough, metal;
                 public Color emissive; public bool twoSided; }

    static readonly Mat[] Materials = new Mat[] {
        new Mat { name = "wall_wood", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.72f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "bench_wood", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.55f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "wall_plaster", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.85f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "ceiling", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.85f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "floor_green", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.95f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "floor_black", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.98f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "target_face", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.9f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "sius_box", color = new Color(0.5f, 0.665f, 0.5f), alpha = 1f, rough = 0.6f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "sius_box_front", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.6f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "lane_number", color = new Color(1f, 1f, 1f), alpha = 1f, rough = 0.7f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "light_panel", color = new Color(1f, 1f, 0.97f), alpha = 1f, rough = 0.4f, metal = 0f, emissive = new Color(1f, 0.98f, 0.92f), twoSided = false },
        new Mat { name = "metal_frame", color = new Color(0.3f, 0.32f, 0.35f), alpha = 1f, rough = 0.35f, metal = 0.9f, emissive = new Color(0f, 0f, 0f), twoSided = false },
        new Mat { name = "glass", color = new Color(0.72f, 0.82f, 0.8f), alpha = 0.16f, rough = 0.04f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = true },
        new Mat { name = "door_glass", color = new Color(0.72f, 0.82f, 0.8f), alpha = 0.2f, rough = 0.04f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = true },
        new Mat { name = "chair_seat", color = new Color(0.1f, 0.2f, 0.36f), alpha = 1f, rough = 0.75f, metal = 0f, emissive = new Color(0f, 0f, 0f), twoSided = false },
    };

    static readonly Vector4[] Lamps = new Vector4[] {   // x, y, z, candela
        new Vector4(-19.5f, 5.9f, -1.5f, 2200f),
        new Vector4(-13.5f, 5.9f, -1.5f, 2200f),
        new Vector4(-7.5f, 5.9f, -1.5f, 2200f),
        new Vector4(-1.5f, 5.9f, -1.5f, 2200f),
        new Vector4(4.5f, 5.9f, -1.5f, 2200f),
        new Vector4(10.5f, 5.9f, -1.5f, 2200f),
        new Vector4(16.5f, 5.9f, -1.5f, 2200f),
        new Vector4(-19.5f, 5.9f, -7.5f, 2200f),
        new Vector4(-13.5f, 5.9f, -7.5f, 2200f),
        new Vector4(-7.5f, 5.9f, -7.5f, 2200f),
        new Vector4(-1.5f, 5.9f, -7.5f, 2200f),
        new Vector4(4.5f, 5.9f, -7.5f, 2200f),
        new Vector4(10.5f, 5.9f, -7.5f, 2200f),
        new Vector4(16.5f, 5.9f, -7.5f, 2200f),
        new Vector4(-19.5f, 5.9f, -13.5f, 2200f),
        new Vector4(-13.5f, 5.9f, -13.5f, 2200f),
        new Vector4(-7.5f, 5.9f, -13.5f, 2200f),
        new Vector4(-1.5f, 5.9f, -13.5f, 2200f),
        new Vector4(4.5f, 5.9f, -13.5f, 2200f),
        new Vector4(10.5f, 5.9f, -13.5f, 2200f),
        new Vector4(16.5f, 5.9f, -13.5f, 2200f),
        new Vector4(-19.5f, 5.9f, -19.5f, 2200f),
        new Vector4(-13.5f, 5.9f, -19.5f, 2200f),
        new Vector4(-7.5f, 5.9f, -19.5f, 2200f),
        new Vector4(-1.5f, 5.9f, -19.5f, 2200f),
        new Vector4(4.5f, 5.9f, -19.5f, 2200f),
        new Vector4(10.5f, 5.9f, -19.5f, 2200f),
        new Vector4(16.5f, 5.9f, -19.5f, 2200f),
        new Vector4(-19.5f, 5.9f, -25.5f, 2200f),
        new Vector4(-13.5f, 5.9f, -25.5f, 2200f),
        new Vector4(-7.5f, 5.9f, -25.5f, 2200f),
        new Vector4(-1.5f, 5.9f, -25.5f, 2200f),
        new Vector4(4.5f, 5.9f, -25.5f, 2200f),
        new Vector4(10.5f, 5.9f, -25.5f, 2200f),
        new Vector4(16.5f, 5.9f, -25.5f, 2200f),
    };

    [MenuItem("Tools/Range/Fix Materials (URP)")]
    static void FixMaterials()
    {
        Shader lit = Shader.Find("Universal Render Pipeline/Lit");
        if (lit == null) { Debug.LogError("URP/Lit not found - is this project on URP?"); return; }

        int touched = 0;
        foreach (Mat m in Materials)
        {
            foreach (string guid in AssetDatabase.FindAssets("t:Material " + m.name))
            {
                var mat = AssetDatabase.LoadAssetAtPath<Material>(AssetDatabase.GUIDToAssetPath(guid));
                if (mat == null || mat.name != m.name) continue;

                mat.shader = lit;
                Color c = m.color; c.a = m.alpha;
                mat.SetColor("_BaseColor", c);
                mat.SetFloat("_Smoothness", 1f - m.rough);   // glTF roughness is the inverse
                mat.SetFloat("_Metallic", m.metal);
                mat.SetFloat("_Cull", m.twoSided ? 0f : 2f); // 0 = render both faces

                if (m.emissive.maxColorComponent > 0f)
                {
                    mat.EnableKeyword("_EMISSION");
                    mat.SetColor("_EmissionColor", m.emissive);
                    mat.globalIlluminationFlags = MaterialGlobalIlluminationFlags.BakedEmissive;
                }

                if (m.alpha < 1f)
                {
                    // URP transparency is a set of switches, not one property; miss any of
                    // them and the glass renders as an opaque sheet.
                    mat.SetFloat("_Surface", 1f);
                    mat.SetFloat("_Blend", 0f);
                    mat.SetFloat("_SrcBlend", (float)UnityEngine.Rendering.BlendMode.SrcAlpha);
                    mat.SetFloat("_DstBlend", (float)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
                    mat.SetFloat("_ZWrite", 0f);
                    mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
                    mat.renderQueue = (int)UnityEngine.Rendering.RenderQueue.Transparent;
                }
                EditorUtility.SetDirty(mat);
                touched++;
            }
        }
        AssetDatabase.SaveAssets();
        Debug.Log($"Range: set up {touched} materials.");
    }

    [MenuItem("Tools/Range/Build Ceiling Lights")]
    static void BuildLights()
    {
        var root = new GameObject("Range Ceiling Lights");
        Undo.RegisterCreatedObjectUndo(root, "Build Ceiling Lights");
        foreach (Vector4 l in Lamps)
        {
            var go = new GameObject("Lamp");
            go.transform.SetParent(root.transform);
            go.transform.position = new Vector3(l.x, l.y, l.z);
            var light = go.AddComponent<Light>();
            light.type = LightType.Point;
            light.range = 12f;
            light.color = new Color(1f, 0.97f, 0.92f);
            light.intensity = l.w / CandelaPerUnit;
            // Baked, not realtime: 35 realtime point lights is not a Quest 3 budget.
            light.lightmapBakeType = LightmapBakeType.Baked;
            light.shadows = LightShadows.None;
            GameObjectUtility.SetStaticEditorFlags(go, StaticEditorFlags.ContributeGI);
        }
        Debug.Log($"Range: built {Lamps.Length} baked lamps. Bake with Window > Rendering > Lighting.");
    }

    [MenuItem("Tools/Range/Add Colliders")]
    static void AddColliders()
    {
        // Everything a player can bump into. The lane signs, target cards and light panels
        // are decoration, and colliders on them would only cost collision checks.
        var solid = new HashSet<string> {
            "floor_green", "floor_black", "wall_wood", "wall_plaster", "ceiling",
            "bench_wood", "chair_seat", "metal_frame", "sius_box", "sius_box_front",
            "glass", "door_glass"
        };
        int n = 0;
        foreach (var mf in Object.FindObjectsOfType<MeshFilter>())
        {
            string baseName = mf.gameObject.name.Split('.')[0];
            if (!solid.Contains(baseName) || mf.GetComponent<MeshCollider>() != null) continue;
            Undo.AddComponent<MeshCollider>(mf.gameObject);
            n++;
        }
        Debug.Log($"Range: added {n} mesh colliders.");
    }
}
